[package]
name = "beater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
librespot = { git = "https://github.com/beater-rs/librespot" }
thiserror = "1.0"

[dev-dependencies]
simplelog = "0.12"
log = "0.4"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
