[package]
name = "beater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librespot = { git = "https://github.com/beater-rs/librespot", branch = "new-api" }
thiserror = "1.0"

[dev-dependencies]
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
