[package]
name = "beater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false


[dependencies]
librespot = { git = "https://github.com/librespot-org/librespot", branch = "new-api" }

[dev-dependencies]
log = "0.4"
simplelog = "0.12"
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.1"
