name: CI

on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - "v*.*.*"

jobs:
    test:
        name: Test
        needs: [style]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                build: [stable, beta, nightly]

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.build }}
                  profile: minimal
                  override: true

            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: ${{ matrix.features }}
              env:
                  SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
                  SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}

    deploy-docs:
        name: Deploy Docs
        needs: [test]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Build Documentation
              run: cargo doc --all

            - name: Deploy Docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./target/doc
                  force_orphan: true

    create-linux-releases:
        name: Release Linux Targets
        needs: [test]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - aarch64-unknown-linux-gnu
                    - armv7-unknown-linux-gnueabihf
                    - i686-unknown-linux-gnu
                    - arm-unknown-linux-gnueabi
                    - x86_64-unknown-linux-gnu

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  target: ${{ matrix.target }}

            - name: Build Target
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --features bin --target ${{ matrix.target }}

            - name: Rename Build Files
              run: mv target/${{ matrix.target }}/release/beater target/${{ matrix.target }}/release/beater-${{ matrix.target }}

            - name: Publish
              uses: softprops/action-gh-release@v1
              # TODO: if any of the build step fails, the release should be deleted.
              with:
                  files: target/${{ matrix.target }}/release/beater-${{ matrix.target }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    create-windows-releases:
        name: Release Windows Targets
        needs: [test]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - x86_64-pc-windows-gnu
                    - i686-pc-windows-gnu

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  target: ${{ matrix.target }}

            - name: Build Target
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --features bin --target ${{ matrix.target }}

            - name: Rename Build Files
              run: mv target/${{ matrix.target }}/release/beater.exe target/${{ matrix.target }}/release/beater-${{ matrix.target }}.exe

            - name: Publish
              uses: softprops/action-gh-release@v1
              # TODO: if any of the build step fails, the release should be deleted.
              with:
                  files: target/${{ matrix.target }}/release/beater-${{ matrix.target }}.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
