name: CI

on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - "v*.*.*"

jobs:
    style:
        name: Check Style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt
                  profile: minimal
                  override: true

            - name: cargo fmt -- --check
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    test:
        name: Test
        needs: [style]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                build: [stable, beta, nightly]

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.build }}
                  profile: minimal
                  override: true

            - name: Install ALSA
              run: sudo apt-get install libasound2-dev -y

            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: ${{ matrix.features }}
              env:
                 SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
                 SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}

    create-release:
        name: deploy
        needs: [test]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                     -  aarch64-unknown-linux-gnu,
                     -  armv7-unknown-linux-gnueabihf,
                     -  i686-unknown-linux-gnu,
                     -  i686-unknown-linux-musl,
                     -  mips-unknown-linux-gnu,
                     -  mips64-unknown-linux-gnuabi64,
                     -  mips64el-unknown-linux-gnuabi64,
                     -  mipsel-unknown-linux-gnu,
                     -  powerpc-unknown-linux-gnu,
                     -  powerpc64-unknown-linux-gnu,
                     -  powerpc64le-unknown-linux-gnu,
                     -  arm-unknown-linux-gnueabi,
                     -  x86_64-unknown-linux-gnu,
                     -  x86_64-unknown-linux-musl
                    
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  target: ${{ matrix.target }}

            - name: Install ALSA
              run: sudo apt-get install libasound2-dev -y

            - name: Build Target
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target ${{ matrix.target }}

            - name: Package
              shell: bash
              run: |
                  cd target/${{ matrix.target }}/release          
                  tar czvf ../../../beater-${{ matrix.target }}.tar.gz beater
                  cd -

            - name: Publish
              uses: softprops/action-gh-release@v1
              # TODO: if any of the build step fails, the release should be deleted.
              with:
                  files: "beater*"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
